# Generated by Django 5.0.3 on 2024-05-19 06:25

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Write the both first and last name of the sitter', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=datetime.date.today, verbose_name='birth date')),
                ('gender', models.CharField(max_length=10)),
                ('nin_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('religion', models.CharField(blank=True, default='Christian', max_length=50)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('sitter_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('contact', models.CharField(blank=True, default='+256XXXXXXXXX', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(verbose_name='birth date')),
                ('location', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('brought_by', models.CharField(default='Dad', max_length=255)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period_of_stay', models.CharField(blank=True, default='Full Day', max_length=50, null=True)),
                ('baby_number', models.CharField(max_length=20, unique=True)),
                ('sitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='babies', to='schoolApp.sitter')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kind', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2024, 5, 19, 6, 25, 8, 929408, tzinfo=datetime.timezone.utc))),
                ('Baby', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schoolApp.baby')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolApp.product')),
            ],
        ),
    ]
