# Generated by Django 5.0.3 on 2024-05-19 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
