# Generated by Django 5.0.3 on 2024-05-19 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0003_alter_baby_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='baby',
            name='baby_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby',
            name='brought_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='baby',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='baby',
            name='fee_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baby',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='baby',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='baby',
            name='parent_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='baby',
            name='period_of_stay',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baby',
            name='sitter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schoolApp.sitter'),
            preserve_default=False,
        ),
    ]
