# Generated by Django 5.0.3 on 2024-05-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0004_alter_baby_arrival_time_alter_baby_baby_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='fee_amount',
        ),
    ]
